export * from "./tenancy";
export * from "./auth";
export * from "./access";
export * from "./audit";
export * from "./academics";
export * from "./students";
export * from "./attendance";
export * from "./exams";
export * from "./communication";
