import {
  BarChart3,
  BookOpen,
  Briefcase,
  CalendarCheck,
  CheckSquare,
  ClipboardList,
  FileText,
  Folder,
  GraduationCap,
  HeartHandshake,
  Home,
  Inbox,
  KeyRound,
  ListChecks,
  Megaphone,
  MessageSquare,
  School,
  ScrollText,
  ShieldCheck,
  User,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/navigation/modules";

export const NAV_ICONS: Record<IconName, LucideIcon> = {
  home: Home,
  users: Users,
  user: User,
  book: BookOpen,
  "calendar-check": CalendarCheck,
  clipboard: ClipboardList,
  "heart-handshake": HeartHandshake,
  wallet: Wallet,
  briefcase: Briefcase,
  megaphone: Megaphone,
  chart: BarChart3,
  "shield-check": ShieldCheck,
  "check-square": CheckSquare,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  school: School,
  message: MessageSquare,
  inbox: Inbox,
  "list-checks": ListChecks,
  folder: Folder,
  key: KeyRound,
  scroll: ScrollText,
};
