import type { Icon } from "@phosphor-icons/react";
import {
  Briefcase,
  CalendarCheck,
  CalendarDots,
  ChalkboardTeacher,
  ChartBar,
  ChatsCircle,
  CheckSquareOffset,
  Exam,
  FileText,
  FolderSimple,
  GraduationCap,
  HandHeart,
  House,
  Key,
  ListChecks,
  Megaphone,
  MegaphoneSimple,
  Notebook,
  Question,
  Scroll,
  SealCheck,
  Student,
  Tray,
  UserCircle,
  Wallet,
} from "@phosphor-icons/react/dist/ssr";
import type { IconName } from "@/lib/navigation/modules";

/**
 * Navigation icons (Phosphor, duotone). Chosen for recognisability over style: a house for home, a tray for the inbox,
 * a question mark for asking — each one also has a text label beside it.
 */
export const NAV_ICONS: Record<IconName, Icon> = {
  home: House,
  users: Student,
  user: UserCircle,
  book: Notebook,
  "calendar-check": CalendarCheck,
  clipboard: Exam,
  "heart-handshake": HandHeart,
  wallet: Wallet,
  briefcase: Briefcase,
  megaphone: Megaphone,
  chart: ChartBar,
  "shield-check": SealCheck,
  "check-square": CheckSquareOffset,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  school: ChalkboardTeacher,
  message: ChatsCircle,
  inbox: Tray,
  "list-checks": ListChecks,
  folder: FolderSimple,
  key: Key,
  scroll: Scroll,
  sparkles: Question,
  "megaphone-plus": MegaphoneSimple,
  calendar: CalendarDots,
};
