/**
 * SYNTHETIC DEMO DATA — fictitious notices, organisations and companies. The seed writes these into `announcement`
 * (scripts/seed-communication.ts); unit tests evaluate their audiences directly.
 */
import type {
  AnnouncementCategory,
  AnnouncementStatus,
  AudienceRule,
  Severity,
} from "@/domains/announcements/types";

const at = (iso: string) => new Date(iso).toISOString();

export interface SeedAnnouncement {
  id: string;
  title: string;
  summary: string;
  body: string[];
  category: AnnouncementCategory;
  severity: Severity;
  /** Persona who wrote it (personas.ts); null for offices without an account. */
  authorKey: string | null;
  author: string;
  authorRole: string;
  status: AnnouncementStatus;
  /** Publication time — or, for drafts and pending notices, when they were written. */
  publishedAt: string;
  expiresAt: string | null;
  deadline: string | null;
  requiresAck: boolean;
  sendEmail: boolean;
  audience: AudienceRule;
  /** Generated as small synthetic PDFs by the seed. */
  attachments: { name: string }[];
  cta: { label: string; phase: number } | null;
}

export const ANNOUNCEMENTS: SeedAnnouncement[] = [
  {
    id: "an-rain-advisory",
    title: "Campus closed on 7 October — heavy rainfall advisory",
    summary: "All classes and internal assessments on Wednesday 7 Oct are suspended. Hostels remain open.",
    body: [
      "Following the district administration's heavy rainfall advisory, both City Campus and Tech Campus will remain closed on Wednesday, 7 October 2026.",
      "Internal assessments scheduled for 7 October are postponed; revised dates will be published by the respective departments.",
      "Hostel residents should stay within hostel premises. The hostel helpdesk will remain staffed throughout the day.",
    ],
    category: "emergency",
    severity: "critical",
    author: "Dr. Meera Raghavan",
    authorRole: "Principal",
    authorKey: "principal",
    status: "published",
    publishedAt: at("2026-10-06T07:45:00+05:30"),
    expiresAt: at("2026-10-08T00:00:00+05:30"),
    deadline: null,
    requiresAck: true,
    sendEmail: true,
    audience: { kind: "institution", audience: "everyone" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-see-nov",
    title: "Semester End Examinations, November 2026 — schedule and hall tickets",
    summary:
      "SEE for odd semester begins 16 November. Hall tickets downloadable from 5 November for eligible students.",
    body: [
      "The Semester End Examinations (SEE) for all odd-semester programmes will commence on Monday, 16 November 2026.",
      "Hall tickets will be available from 5 November 2026. Only students meeting the 75% attendance requirement and with no fee dues will be issued hall tickets.",
      "Students with attendance shortage must contact their class incharge before 30 October to review condonation eligibility.",
    ],
    category: "examinations",
    severity: "high",
    author: "Dr. Leela Krishnan",
    authorRole: "Controller of Examinations",
    authorKey: "exam_controller",
    status: "published",
    publishedAt: at("2026-10-05T16:00:00+05:30"),
    expiresAt: at("2026-11-30T23:59:00+05:30"),
    deadline: at("2026-10-30T17:00:00+05:30"),
    requiresAck: true,
    sendEmail: true,
    audience: { kind: "institution", audience: "students" },
    attachments: [{ name: "SEE-Nov-2026-Timetable.pdf" }],
    cta: { label: "Download hall ticket", phase: 4 },
  },
  {
    id: "an-cse-ia2",
    title: "CSE Internal Assessment II — revised timetable",
    summary: "IA-II for all CSE years moves to 12–16 October following the 7 October closure.",
    body: [
      "Internal Assessment II for all CSE sections is rescheduled to 12–16 October 2026.",
      "Seating arrangements will be displayed outside the department office one day prior.",
    ],
    category: "examinations",
    severity: "normal",
    author: "Prof. Arvind Kulkarni",
    authorRole: "HOD, CSE",
    authorKey: "hod_cse",
    status: "published",
    publishedAt: at("2026-10-06T08:30:00+05:30"),
    expiresAt: at("2026-10-17T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "department", departmentCode: "CSE", audience: "everyone" },
    attachments: [{ name: "CSE-IA2-Revised.pdf" }],
    cta: null,
  },
  {
    id: "an-ece-ia2",
    title: "ECE Internal Assessment II — lab evaluation slots",
    summary: "Lab evaluation slots for ECE years 2–4 are open for booking until 9 October.",
    body: ["ECE students should book a lab evaluation slot with their lab instructor by 9 October 2026."],
    category: "examinations",
    severity: "normal",
    author: "Dr. Lakshmi Iyer",
    authorRole: "HOD, ECE",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-10-05T11:00:00+05:30"),
    expiresAt: at("2026-10-16T00:00:00+05:30"),
    deadline: at("2026-10-09T17:00:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "department", departmentCode: "ECE", audience: "students" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-section-mentor",
    title: "3-CSE-A: mentor meeting slots this Friday",
    summary: "Students below 75% attendance must book a slot. Others may book optionally.",
    body: [
      "Mentor meetings for 3-CSE-A will be held on Friday, 9 October between 14:00 and 17:00 in TB-204.",
      "Students currently below the 75% attendance threshold are required to attend and bring a parent contact number.",
    ],
    category: "academic",
    severity: "normal",
    author: "Ms. Kavya Nair",
    authorRole: "Class Incharge, 3-CSE-A",
    authorKey: "class_incharge",
    status: "published",
    publishedAt: at("2026-10-05T18:10:00+05:30"),
    expiresAt: at("2026-10-10T00:00:00+05:30"),
    deadline: at("2026-10-09T14:00:00+05:30"),
    requiresAck: true,
    sendEmail: false,
    audience: { kind: "section", sectionId: "CSE-3-A", audience: "families" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-internship-contoso",
    title: "Summer internship 2027 — Contoso Analytics (pre-placement track)",
    summary:
      "Open to 3rd-year CSE and ECE students with CGPA ≥ 7.0 and no active backlogs. Register by 20 October.",
    body: [
      "Contoso Analytics (fictitious) is offering 10-week summer internships with a pre-placement offer track.",
      "Eligibility: B.Tech CSE/ECE, 3rd year, CGPA ≥ 7.0, no active backlogs.",
      "Online assessment on 27 October; interviews in the first week of November.",
    ],
    category: "internships",
    severity: "high",
    author: "Ms. Ritu Chawla",
    authorRole: "Placement Head",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-10-04T10:00:00+05:30"),
    expiresAt: at("2026-10-21T00:00:00+05:30"),
    deadline: at("2026-10-20T23:59:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "placement_eligible", departmentCodes: ["CSE", "ECE"], year: 3 },
    attachments: [{ name: "Contoso-JD.pdf" }],
    cta: { label: "Register", phase: 8 },
  },
  {
    id: "an-drive-northwind",
    title: "Campus drive — Northwind Systems, Graduate Engineer Trainee",
    summary:
      "Final-year B.Tech students: registration closes 12 October. Drive on 22 October at Tech Campus.",
    body: [
      "Northwind Systems (fictitious) will conduct a campus drive for Graduate Engineer Trainee roles.",
      "Eligibility: B.Tech CSE/ECE/EEE, final year, CGPA ≥ 6.5.",
    ],
    category: "placement",
    severity: "high",
    author: "Ms. Ritu Chawla",
    authorRole: "Placement Head",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-10-03T09:00:00+05:30"),
    expiresAt: at("2026-10-23T00:00:00+05:30"),
    deadline: at("2026-10-12T17:00:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "placement_eligible", departmentCodes: ["CSE", "ECE", "EEE"], year: 4 },
    attachments: [],
    cta: { label: "Register", phase: 8 },
  },
  {
    id: "an-fee-deadline",
    title: "Odd semester fee — last date 15 October",
    summary:
      "A late fee of ₹500 per week applies after 15 October. Students with dues will not receive hall tickets.",
    body: [
      "The last date for payment of odd-semester tuition fees is 15 October 2026.",
      "A late fee of ₹500 per week applies thereafter. Students with outstanding dues will not be issued SEE hall tickets.",
    ],
    category: "scholarships",
    severity: "high",
    author: "Accounts Office",
    authorRole: "Finance",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-10-01T10:00:00+05:30"),
    expiresAt: at("2026-10-31T00:00:00+05:30"),
    deadline: at("2026-10-15T17:00:00+05:30"),
    requiresAck: false,
    sendEmail: true,
    audience: { kind: "institution", audience: "families" },
    attachments: [],
    cta: { label: "Pay fee", phase: 7 },
  },
  {
    id: "an-scholarship",
    title: "Post-matric scholarship renewal — document submission",
    summary:
      "Renewal applicants must upload income certificate and previous semester marks card by 25 October.",
    body: [
      "Students renewing the state post-matric scholarship must submit documents to the scholarship desk by 25 October 2026.",
    ],
    category: "scholarships",
    severity: "normal",
    author: "Scholarship Cell",
    authorRole: "Student Welfare",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-09-29T12:00:00+05:30"),
    expiresAt: at("2026-10-26T00:00:00+05:30"),
    deadline: at("2026-10-25T17:00:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "institution", audience: "students" },
    attachments: [{ name: "Scholarship-Checklist.pdf" }],
    cta: null,
  },
  {
    id: "an-revaluation",
    title: "Revaluation results — even semester 2025–26",
    summary: "Revaluation outcomes are published. Updated grade cards are available from the exam section.",
    body: ["Results of revaluation for the even semester examinations (May 2026) have been published."],
    category: "results",
    severity: "normal",
    author: "Dr. Leela Krishnan",
    authorRole: "Controller of Examinations",
    authorKey: "exam_controller",
    status: "published",
    publishedAt: at("2026-09-24T15:00:00+05:30"),
    expiresAt: at("2026-10-24T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "institution", audience: "students" },
    attachments: [{ name: "Revaluation-Results-May-2026.pdf" }],
    cta: null,
  },
  {
    id: "an-hackathon",
    title: "CSE Hackathon 2026 — team registrations open",
    summary: "24-hour hackathon on 31 October. Teams of 2–4. Open to all CSE students.",
    body: [
      "The department's annual 24-hour hackathon will be held on 31 October 2026 in the Innovation Lab.",
    ],
    category: "events",
    severity: "low",
    author: "Mr. Karthik Rao",
    authorRole: "Faculty, CSE",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-10-02T14:00:00+05:30"),
    expiresAt: at("2026-11-01T00:00:00+05:30"),
    deadline: at("2026-10-24T23:59:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "department", departmentCode: "CSE", audience: "students" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-attendance-window",
    title: "Faculty: daily attendance submission closes at 18:00",
    summary: "Attendance not submitted by 18:00 will require a correction request approved by the HOD.",
    body: [
      "To keep shortage alerts accurate, attendance for each session must be submitted by 18:00 the same day.",
    ],
    category: "administrative",
    severity: "normal",
    author: "Dr. Meera Raghavan",
    authorRole: "Principal",
    authorKey: "principal",
    status: "published",
    publishedAt: at("2026-09-30T09:00:00+05:30"),
    expiresAt: null,
    deadline: null,
    requiresAck: true,
    sendEmail: false,
    audience: { kind: "institution", audience: "staff" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-naac-evidence",
    title: "NAAC Criterion 2 evidence — department submissions due",
    summary:
      "HODs to upload teaching-learning evidence (Criterion 2.3 and 2.6) to the IQAC workspace by 31 October.",
    body: [
      "The IQAC requests each department to upload Criterion 2.3 and 2.6 evidence for the 2025–26 academic year.",
    ],
    category: "compliance",
    severity: "normal",
    author: "IQAC Coordinator",
    authorRole: "Compliance",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-09-28T11:00:00+05:30"),
    expiresAt: at("2026-11-01T00:00:00+05:30"),
    deadline: at("2026-10-31T17:00:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "institution", audience: "staff" },
    attachments: [{ name: "Criterion-2-Template.xlsx" }],
    cta: null,
  },
  {
    id: "an-library",
    title: "Central library open until 22:00 during exam season",
    summary: "Extended hours apply from 1 November to 30 November on both campuses.",
    body: ["The central library will remain open until 22:00 from 1 to 30 November 2026."],
    category: "administrative",
    severity: "low",
    author: "Chief Librarian",
    authorRole: "Library",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-09-27T10:00:00+05:30"),
    expiresAt: at("2026-12-01T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "institution", audience: "everyone" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-mba-guest",
    title: "MBA guest lecture — Supply chain resilience",
    summary: "Guest session for MBA year 2 on 8 October, 11:00, Seminar Hall 1.",
    body: ["MBA second-year students are required to attend the guest lecture on supply chain resilience."],
    category: "events",
    severity: "normal",
    author: "Dr. Nandini Sen",
    authorRole: "HOD, MBA",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-10-03T12:00:00+05:30"),
    expiresAt: at("2026-10-09T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "year", departmentCode: "MBA", year: 2, audience: "students" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-orientation",
    title: "Orientation programme for first-year students",
    summary: "Orientation week ran 18–22 August. Session recordings remain available in the library portal.",
    body: ["The orientation programme for the 2026 entering batch was held from 18 to 22 August 2026."],
    category: "general",
    severity: "low",
    author: "Dean, Student Affairs",
    authorRole: "Dean",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-08-10T10:00:00+05:30"),
    expiresAt: at("2026-08-23T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "institution", audience: "students" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-cse-sports",
    title: "Inter-department sports meet — CSE team trials",
    summary: "Trials for cricket, football and athletics held 14–16 September.",
    body: ["Team trials for the inter-department sports meet were held on 14–16 September."],
    category: "events",
    severity: "low",
    author: "Physical Education",
    authorRole: "Sports",
    authorKey: null,
    status: "published",
    publishedAt: at("2026-09-08T10:00:00+05:30"),
    expiresAt: at("2026-09-17T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "department", departmentCode: "CSE", audience: "students" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-cse-electives",
    title: "B.Tech CSE: open elective preferences for semester 6",
    summary: "Third-year CSE students list three open-elective preferences by 16 October.",
    body: [
      "Open electives for semester 6 (2027) are allotted by preference and CGPA. Submit three preferences in order.",
      "Electives with fewer than 20 registrations will not be offered; affected students keep their next preference.",
    ],
    category: "academic",
    severity: "normal",
    author: "Dr. Sunita Menon",
    authorRole: "Programme Coordinator",
    authorKey: "programme_coordinator",
    status: "pending",
    publishedAt: at("2026-10-05T15:20:00+05:30"),
    expiresAt: at("2026-10-17T00:00:00+05:30"),
    deadline: at("2026-10-16T17:00:00+05:30"),
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "year", departmentCode: "CSE", year: 3, audience: "students" },
    attachments: [{ name: "Open-Electives-Sem6.pdf" }],
    cta: null,
  },
  {
    id: "an-hall-ticket-photo",
    title: "Hall tickets: verify your photograph and name by 20 October",
    summary:
      "Check the photograph and the spelling of your name on the exam portal; corrections close on 20 October.",
    body: [
      "Hall tickets for the November 2026 examinations print the photograph and name held by the examination cell.",
      "Students whose photograph is missing or older than two years must submit a new passport-size photograph to the examination cell by 20 October.",
    ],
    category: "examinations",
    severity: "high",
    author: "Dr. Leela Krishnan",
    authorRole: "Controller of Examinations",
    authorKey: "exam_controller",
    status: "pending",
    publishedAt: at("2026-10-06T08:45:00+05:30"),
    expiresAt: at("2026-10-21T00:00:00+05:30"),
    deadline: at("2026-10-20T17:00:00+05:30"),
    requiresAck: true,
    sendEmail: true,
    audience: { kind: "institution", audience: "students" },
    attachments: [],
    cta: null,
  },
  {
    id: "an-lab-records",
    title: "3-CSE-A: lab records before IA-II",
    summary: "Operating Systems lab records are due on the first day of IA-II.",
    body: ["Bring completed and signed Operating Systems lab records on 12 October."],
    category: "academic",
    severity: "normal",
    author: "Ms. Kavya Nair",
    authorRole: "Class Incharge, 3-CSE-A",
    authorKey: "class_incharge",
    status: "draft",
    publishedAt: at("2026-10-06T09:05:00+05:30"),
    expiresAt: at("2026-10-13T00:00:00+05:30"),
    deadline: null,
    requiresAck: false,
    sendEmail: false,
    audience: { kind: "section", sectionId: "CSE-3-A", audience: "students" },
    attachments: [],
    cta: null,
  },
];
